# -*- coding: utf-8 -*-
"""vsppytube.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZQnFHTxRazjBfHDi0JHagxkrr7NJ-n2J
"""

!pip install pytube
!pip install ffmpeg-python

from pytube import YouTube
import ffmpeg
link=input("Enter Video Link:")
yt=YouTube(link)
yt.title

yt.streams.all()

dwdvideo=yt.streams.get_by_itag(137).download(filename="video.mp4")
dwdaudio=yt.streams.get_by_itag(140).download(filename="audio.mp4")

ip1=ffmpeg.input('./video.mp4')
ip2=ffmpeg.input('./audio.mp4')
out=ffmpeg.output(ip1,ip2,'./out1.mp4',acodec='copy',vcodec='copy')
f1=out.run()